set(__QT_DEPLOY_TARGET_workstation_FILE H:/naksha lidar C C++/WorkstationCAD/build-gui/libworkstation.a)
set(__QT_DEPLOY_TARGET_workstation_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_wk_tests_FILE H:/naksha lidar C C++/WorkstationCAD/build-gui/wk_tests.exe)
set(__QT_DEPLOY_TARGET_wk_tests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_wk_tests_RUNTIME_DLLS )
set(__QT_DEPLOY_TARGET_wk_tests2_FILE H:/naksha lidar C C++/WorkstationCAD/build-gui/wk_tests2.exe)
set(__QT_DEPLOY_TARGET_wk_tests2_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_wk_tests2_RUNTIME_DLLS )
set(__QT_DEPLOY_TARGET_wk_tests3_FILE H:/naksha lidar C C++/WorkstationCAD/build-gui/wk_tests3.exe)
set(__QT_DEPLOY_TARGET_wk_tests3_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_wk_tests3_RUNTIME_DLLS )
set(__QT_DEPLOY_TARGET_wk_demo_FILE H:/naksha lidar C C++/WorkstationCAD/build-gui/wk_demo.exe)
set(__QT_DEPLOY_TARGET_wk_demo_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_wk_demo_RUNTIME_DLLS )
set(__QT_DEPLOY_TARGET_wk_tests4_FILE H:/naksha lidar C C++/WorkstationCAD/build-gui/wk_tests4.exe)
set(__QT_DEPLOY_TARGET_wk_tests4_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_wk_tests4_RUNTIME_DLLS )
set(__QT_DEPLOY_TARGET_wk_gui_FILE H:/naksha lidar C C++/WorkstationCAD/build-gui/wk_gui.exe)
set(__QT_DEPLOY_TARGET_wk_gui_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_wk_gui_RUNTIME_DLLS H:/6.11.2/mingw_64/bin/Qt6Widgets.dll;H:/6.11.2/mingw_64/bin/Qt6Gui.dll;H:/6.11.2/mingw_64/bin/Qt6Core.dll)
set(__QT_DEPLOY_TARGET_wk_gui_smoke_FILE H:/naksha lidar C C++/WorkstationCAD/build-gui/wk_gui_smoke.exe)
set(__QT_DEPLOY_TARGET_wk_gui_smoke_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_wk_gui_smoke_RUNTIME_DLLS H:/6.11.2/mingw_64/bin/Qt6Widgets.dll;H:/6.11.2/mingw_64/bin/Qt6Gui.dll;H:/6.11.2/mingw_64/bin/Qt6Core.dll)
set(__QT_DEPLOY_TARGET_wk_pc_tests_FILE H:/naksha lidar C C++/WorkstationCAD/build-gui/wk_pc_tests.exe)
set(__QT_DEPLOY_TARGET_wk_pc_tests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_wk_pc_tests_RUNTIME_DLLS )
set(__QT_DEPLOY_TARGET_wk_pc2_tests_FILE H:/naksha lidar C C++/WorkstationCAD/build-gui/wk_pc2_tests.exe)
set(__QT_DEPLOY_TARGET_wk_pc2_tests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_wk_pc2_tests_RUNTIME_DLLS )
set(__QT_DEPLOY_TARGET_wk_pc3_tests_FILE H:/naksha lidar C C++/WorkstationCAD/build-gui/wk_pc3_tests.exe)
set(__QT_DEPLOY_TARGET_wk_pc3_tests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_wk_pc3_tests_RUNTIME_DLLS )
set(__QT_DEPLOY_TARGET_wk_pod_tests_FILE H:/naksha lidar C C++/WorkstationCAD/build-gui/wk_pod_tests.exe)
set(__QT_DEPLOY_TARGET_wk_pod_tests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_wk_pod_tests_RUNTIME_DLLS )
set(__QT_DEPLOY_TARGET_wk_pod_handler_tests_FILE H:/naksha lidar C C++/WorkstationCAD/build-gui/wk_pod_handler_tests.exe)
set(__QT_DEPLOY_TARGET_wk_pod_handler_tests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_wk_pod_handler_tests_RUNTIME_DLLS )
set(__QT_DEPLOY_TARGET_wk_pod_datasource_tests_FILE H:/naksha lidar C C++/WorkstationCAD/build-gui/wk_pod_datasource_tests.exe)
set(__QT_DEPLOY_TARGET_wk_pod_datasource_tests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_wk_pod_datasource_tests_RUNTIME_DLLS )
set(__QT_DEPLOY_TARGET_wk_pod_integration_tests_FILE H:/naksha lidar C C++/WorkstationCAD/build-gui/wk_pod_integration_tests.exe)
set(__QT_DEPLOY_TARGET_wk_pod_integration_tests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_wk_pod_integration_tests_RUNTIME_DLLS )
